### ISSUE TITLE
Unable to save the user into the database

### ISSUE THREAD

**Issue by tommy4111** [NaveedShahid/Voice-Authentication-CNN#3]
Loading model weights from [voice_auth_model_cnn]....
Processing enroll sample....
Error processing the input audio file. Make sure the path.
Unable to save the user into the database.

**Comment by NaveedShahid** [comment]
Hi, did you verify the audio path you are passing to the function is
correct?

**Comment by tommy4111** [comment]
Oh ok, the audio path is an actual file not mic in put =)
